// Copyright 2017-2022 @polkadot/app-board-virginia authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/app-board-virginia', path: 'auto', type: 'auto', version: '0.109.2-20' };
